import { PrismaService } from '../prisma/prisma.service';
import { CreateVideoDto } from './dto/create-video.dto';
import { VideoCategory, VideoDifficulty } from '@prisma/client';
export declare class VideosService {
    private prisma;
    constructor(prisma: PrismaService);
    findAllAdmin(): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }[]>;
    findAll(filters?: {
        category?: VideoCategory;
        difficulty?: VideoDifficulty;
    }): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }[]>;
    findById(id: string): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }>;
    create(dto: CreateVideoDto): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }>;
    updateHlsUrl(id: string, hlsUrl: string): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }>;
    publish(id: string): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }>;
    delete(id: string): Promise<{
        id: string;
        description: string;
        difficulty: import(".prisma/client").$Enums.VideoDifficulty;
        thumbnailUrl: string;
        createdAt: Date;
        updatedAt: Date;
        title: string;
        category: import(".prisma/client").$Enums.VideoCategory;
        durationSeconds: number;
        hlsUrl: string | null;
        s3RawKey: string;
        choreographyUrl: string | null;
        preprocessingStatus: import(".prisma/client").$Enums.PreprocessingStatus;
        preprocessingError: string | null;
        preprocessingJobId: string | null;
        isPublished: boolean;
    }>;
}
//# sourceMappingURL=videos.service.d.ts.map