'use client';

/**
 * V2DailyBrief — flagship hero card on the dashboard.
 * Shows the AI Coach's plan for today: mood-driven gradient,
 * structured workout, motivational hook, CTA to start training.
 */

import Link from 'next/link';
import type { DailyBrief, DailyBriefMood } from '@/lib/api';

const moodTheme: Record<
  DailyBriefMood,
  { gradient: string; accent: string; chip: string; ring: string }
> = {
  push: {
    gradient: 'from-[#FF375F]/30 via-[#FF9F0A]/15 to-transparent',
    accent: '#FF375F',
    chip: 'bg-[#FF375F]/15 text-[#FF375F] border-[#FF375F]/30',
    ring: 'ring-[#FF375F]/40',
  },
  maintain: {
    gradient: 'from-[#A8FF00]/25 via-[#00E5FF]/10 to-transparent',
    accent: '#A8FF00',
    chip: 'bg-[#A8FF00]/15 text-[#A8FF00] border-[#A8FF00]/30',
    ring: 'ring-[#A8FF00]/35',
  },
  recover: {
    gradient: 'from-[#00E5FF]/25 via-[#7C3AED]/10 to-transparent',
    accent: '#00E5FF',
    chip: 'bg-[#00E5FF]/15 text-[#00E5FF] border-[#00E5FF]/30',
    ring: 'ring-[#00E5FF]/35',
  },
};

const moodLabel: Record<DailyBriefMood, string> = {
  push: 'PUSH DAY',
  maintain: 'MAINTAIN',
  recover: 'RECOVER',
};

export function V2DailyBrief({ brief }: { brief: DailyBrief }) {
  const theme = moodTheme[brief.mood];

  return (
    <section className="mb-32">
      <div className="mb-3 text-[10px] font-semibold uppercase tracking-[0.3em] text-white/40">
        AI Coach · Brief pro dnešek
      </div>

      {/* Hero card with gradient */}
      <div
        className={`relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br ${theme.gradient} p-8 sm:p-12`}
      >
        {/* mood chip + recovery score top-right */}
        <div className="mb-8 flex items-start justify-between">
          <span
            className={`inline-flex items-center rounded-full border px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.25em] ${theme.chip}`}
          >
            {moodLabel[brief.mood]}
          </span>
          <div className="text-right">
            <div className="text-[9px] font-semibold uppercase tracking-[0.25em] text-white/40">
              Recovery
            </div>
            <div
              className="font-bold tabular-nums text-white"
              style={{ fontSize: '1.75rem', letterSpacing: '-0.04em', lineHeight: 1 }}
            >
              {brief.recoveryScore}
              <span className="text-base text-white/40">/100</span>
            </div>
          </div>
        </div>

        {/* Headline */}
        <h2
          className="mb-4 max-w-2xl font-bold tracking-tight text-white"
          style={{ fontSize: 'clamp(2rem, 5vw, 3.5rem)', letterSpacing: '-0.04em', lineHeight: 1.05 }}
        >
          {brief.headline}
        </h2>

        {/* Workout meta */}
        <div className="mb-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-white/65">
          <span className="font-semibold text-white">{brief.workout.title}</span>
          <span>·</span>
          <span>~{brief.workout.estimatedMinutes} min</span>
          <span>·</span>
          <span>{brief.workout.exercises.length} cviků</span>
        </div>

        {/* Rationale */}
        <p className="mb-8 max-w-2xl text-base leading-relaxed text-white/75">
          {brief.rationale}
        </p>

        {/* CTAs */}
        <div className="flex flex-wrap gap-3">
          <Link
            href="/gym/start"
            className="group inline-flex items-center gap-2 rounded-full bg-white px-7 py-4 text-sm font-semibold tracking-tight text-black transition hover:scale-[1.03]"
          >
            Začít trénink
            <span className="transition group-hover:translate-x-1">→</span>
          </Link>
          <Link
            href="/habity"
            className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/5 px-7 py-4 text-sm font-semibold tracking-tight text-white/80 transition hover:bg-white/10"
          >
            Upravit recovery
          </Link>
        </div>

        {/* Source watermark */}
        <div className="mt-8 text-[9px] font-semibold uppercase tracking-[0.3em] text-white/25">
          {brief.source === 'claude' ? '✦ Generated by Claude Haiku' : '✦ Rules-based fallback'}
        </div>
      </div>

      {/* Warmup */}
      <div className="mt-10 grid grid-cols-1 gap-10 lg:grid-cols-3">
        <div>
          <div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
            Rozcvička
          </div>
          <p className="text-base leading-relaxed text-white/80">{brief.workout.warmup}</p>
        </div>
        <div>
          <div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
            Nutriční tip
          </div>
          <p className="text-base leading-relaxed text-white/80">{brief.nutritionTip}</p>
        </div>
        <div>
          <div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
            Pokud nemáš den
          </div>
          <p className="text-base leading-relaxed text-white/60">{brief.alternativeIfTired}</p>
        </div>
      </div>

      {/* Exercise list */}
      <div className="mt-12">
        <div className="mb-5 text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
          Plán cviků
        </div>
        <ol className="divide-y divide-white/10 border-y border-white/10">
          {brief.workout.exercises.map((ex, i) => (
            <li key={i} className="grid grid-cols-12 items-center gap-4 py-5">
              <div className="col-span-1 text-xs font-semibold tabular-nums text-white/30">
                {String(i + 1).padStart(2, '0')}
              </div>
              <div className="col-span-7 sm:col-span-6">
                <div className="text-base font-semibold text-white">{ex.nameCs}</div>
                {ex.rationale && (
                  <div className="mt-1 text-xs text-white/45">{ex.rationale}</div>
                )}
              </div>
              <div className="col-span-4 sm:col-span-5 text-right text-sm tabular-nums text-white/75">
                <span className="font-semibold text-white">{ex.sets}×{ex.reps}</span>
                {ex.weightKg != null && (
                  <span className="text-white/40"> · {ex.weightKg}kg</span>
                )}
                <span className="text-white/40"> · RPE {ex.rpe}</span>
              </div>
            </li>
          ))}
        </ol>
        {brief.workout.finisher && (
          <div className="mt-5 rounded-2xl border border-white/10 bg-white/[0.02] p-5">
            <div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
              Finisher
            </div>
            <p className="text-sm text-white/80">{brief.workout.finisher}</p>
          </div>
        )}
      </div>

      {/* Motivational hook */}
      <div className="mt-12 border-l-2 pl-6" style={{ borderColor: theme.accent }}>
        <p
          className="font-bold tracking-tight text-white"
          style={{ fontSize: 'clamp(1.25rem, 2.5vw, 1.75rem)', letterSpacing: '-0.02em' }}
        >
          „{brief.motivationalHook}"
        </p>
      </div>
    </section>
  );
}
