import React, { useEffect, useState, useCallback } from 'react';
import { View, Text, Pressable, Alert } from 'react-native';
import {
  getFitnessProfile,
  updateFitnessProfile,
  generateAIPlan,
} from '../lib/api';
import { V2Screen, V2Display, V2SectionLabel, V2Chip, V2Button, V2Loading, v2 } from '../components/v2/V2';

const GOALS = [
  { v: 'STRENGTH', l: 'Strength' },
  { v: 'HYPERTROPHY', l: 'Hypertrophy' },
  { v: 'ENDURANCE', l: 'Endurance' },
  { v: 'WEIGHT_LOSS', l: 'Weight Loss' },
  { v: 'GENERAL_FITNESS', l: 'General' },
  { v: 'MOBILITY', l: 'Mobility' },
];

const EQUIPMENT = [
  { v: 'barbell', l: 'Barbell' },
  { v: 'dumbbells', l: 'Dumbbells' },
  { v: 'cables', l: 'Cables' },
  { v: 'pullup_bar', l: 'Pull-up bar' },
  { v: 'bench', l: 'Bench' },
  { v: 'rack', l: 'Rack' },
  { v: 'kettlebell', l: 'Kettlebell' },
  { v: 'resistance_bands', l: 'Bands' },
];

export function AICoachScreen({ navigation }: any) {
  const [profile, setProfile] = useState<any>(null);
  const [loadError, setLoadError] = useState(false);
  const [generating, setGenerating] = useState(false);

  const reload = useCallback(() => {
    setLoadError(false);
    getFitnessProfile()
      .then(setProfile)
      .catch(() => setLoadError(true));
  }, []);
  useEffect(reload, [reload]);

  async function save(field: string, value: any) {
    if (!profile) return;
    const prev = profile;
    setProfile({ ...profile, [field]: value });
    try {
      const updated = await updateFitnessProfile({ [field]: value });
      setProfile(updated);
    } catch {
      setProfile(prev);
    }
  }

  async function handleGenerate() {
    setGenerating(true);
    try {
      const plan = await generateAIPlan();
      navigation.navigate('PlanDetail', { id: plan.id });
    } catch {
      Alert.alert('Generation failed', 'Could not generate plan. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  if (loadError) {
    return (
      <V2Screen>
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 }}>
          <Text style={{ color: '#FF375F', fontSize: 16, fontWeight: '600', marginBottom: 16 }}>Failed to load profile</Text>
          <Pressable onPress={reload} style={{ paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, backgroundColor: '#FFF' }}>
            <Text style={{ color: '#000', fontWeight: '700' }}>Retry</Text>
          </Pressable>
        </View>
      </V2Screen>
    );
  }

  if (!profile) return <V2Screen><V2Loading /></V2Screen>;

  return (
    <V2Screen>
      <View style={{ paddingTop: 24, marginBottom: 32 }}>
        <V2SectionLabel>Personalization</V2SectionLabel>
        <V2Display size="xl">AI Coach.</V2Display>
        <Text style={{ color: v2.muted, marginTop: 12, fontSize: 14 }}>
          Plan generated by Claude AI based on your goals and recovery.
        </Text>
      </View>

      {/* Goal */}
      <View style={{ marginBottom: 32 }}>
        <V2SectionLabel>Goal</V2SectionLabel>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 }}>
          {GOALS.map((g) => (
            <V2Chip key={g.v} label={g.l} selected={profile.goal === g.v} onPress={() => save('goal', g.v)} />
          ))}
        </View>
      </View>

      {/* Equipment */}
      <View style={{ marginBottom: 32 }}>
        <V2SectionLabel>Equipment</V2SectionLabel>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 }}>
          {EQUIPMENT.map((eq) => {
            const sel = profile.equipment?.includes(eq.v);
            return (
              <V2Chip
                key={eq.v}
                label={eq.l}
                selected={sel}
                onPress={() => {
                  const cur = profile.equipment || [];
                  save('equipment', sel ? cur.filter((e: string) => e !== eq.v) : [...cur, eq.v]);
                }}
              />
            );
          })}
        </View>
      </View>

      <V2Button onPress={handleGenerate} disabled={generating} full>
        {generating ? 'AI generating plan...' : 'Generate plan →'}
      </V2Button>
    </V2Screen>
  );
}
