import React, { useEffect, useState, useCallback } from 'react';
import { View, Text } from 'react-native';
import {
  getFitnessProfile,
  updateFitnessProfile,
  generateAIPlan,
} from '../lib/api';
import { V2Screen, V2Display, V2SectionLabel, V2Chip, V2Button, v2 } from '../components/v2/V2';
import { useHaptic, LoadingState, ErrorState } from '../components/native';

const GOALS = [
  { v: 'STRENGTH', l: 'Strength' },
  { v: 'HYPERTROPHY', l: 'Hypertrophy' },
  { v: 'ENDURANCE', l: 'Endurance' },
  { v: 'WEIGHT_LOSS', l: 'Weight Loss' },
  { v: 'GENERAL_FITNESS', l: 'General' },
  { v: 'MOBILITY', l: 'Mobility' },
];

const EQUIPMENT = [
  { v: 'barbell', l: 'Barbell' },
  { v: 'dumbbells', l: 'Dumbbells' },
  { v: 'cables', l: 'Cables' },
  { v: 'pullup_bar', l: 'Pull-up bar' },
  { v: 'bench', l: 'Bench' },
  { v: 'rack', l: 'Rack' },
  { v: 'kettlebell', l: 'Kettlebell' },
  { v: 'resistance_bands', l: 'Bands' },
];

export function AICoachScreen({ navigation }: any) {
  const [profile, setProfile] = useState<any>(null);
  const [loadError, setLoadError] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const haptic = useHaptic();

  const reload = useCallback(() => {
    setLoadError(false);
    getFitnessProfile()
      .then(setProfile)
      .catch(() => setLoadError(true));
  }, []);
  useEffect(reload, [reload]);

  async function save(field: string, value: any) {
    if (!profile) return;
    haptic.selection();
    const prev = profile;
    setProfile({ ...profile, [field]: value });
    try {
      const updated = await updateFitnessProfile({ [field]: value });
      setProfile(updated);
    } catch {
      haptic.error();
      setProfile(prev);
    }
  }

  async function handleGenerate() {
    haptic.tap();
    setGenerateError(null);
    setGenerating(true);
    try {
      const plan = await generateAIPlan();
      haptic.success();
      navigation.navigate('PlanDetail', { id: plan.id });
    } catch {
      haptic.error();
      setGenerateError('Could not generate plan. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  if (loadError) {
    return (
      <V2Screen>
        <ErrorState message="Failed to load profile." onRetry={reload} />
      </V2Screen>
    );
  }

  if (!profile) return <V2Screen><LoadingState label="Loading profile" /></V2Screen>;

  return (
    <V2Screen>
      <View style={{ paddingTop: 24, marginBottom: 32 }}>
        <V2SectionLabel>Personalization</V2SectionLabel>
        <V2Display size="xl">AI Coach.</V2Display>
        <Text style={{ color: v2.muted, marginTop: 12, fontSize: 14 }}>
          Plan generated by Claude AI based on your goals and recovery.
        </Text>
      </View>

      {/* Goal */}
      <View style={{ marginBottom: 32 }}>
        <V2SectionLabel>Goal</V2SectionLabel>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 }}>
          {GOALS.map((g) => (
            <V2Chip key={g.v} label={g.l} selected={profile.goal === g.v} onPress={() => save('goal', g.v)} />
          ))}
        </View>
      </View>

      {/* Equipment */}
      <View style={{ marginBottom: 32 }}>
        <V2SectionLabel>Equipment</V2SectionLabel>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 }}>
          {EQUIPMENT.map((eq) => {
            const sel = profile.equipment?.includes(eq.v);
            return (
              <V2Chip
                key={eq.v}
                label={eq.l}
                selected={sel}
                onPress={() => {
                  const cur = profile.equipment || [];
                  save('equipment', sel ? cur.filter((e: string) => e !== eq.v) : [...cur, eq.v]);
                }}
              />
            );
          })}
        </View>
      </View>

      {generateError && (
        <View style={{ marginBottom: 12, backgroundColor: 'rgba(255,55,95,0.10)', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: 'rgba(255,55,95,0.25)' }}>
          <Text style={{ color: v2.red, fontSize: 13 }}>{generateError}</Text>
        </View>
      )}

      <V2Button onPress={handleGenerate} disabled={generating} full>
        {generating ? 'AI generating plan...' : 'Generate plan →'}
      </V2Button>
    </V2Screen>
  );
}
