'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  getFitnessProfile,
  updateFitnessProfile,
  generateAIPlan,
  getAsymmetryReport,
  getBreakRecovery,
  type FitnessProfileData,
  type AsymmetryReport,
  type BreakRecovery,
} from '@/lib/api';

const GOALS = [
  { v: 'STRENGTH', l: 'Strength' },
  { v: 'HYPERTROPHY', l: 'Hypertrophy' },
  { v: 'ENDURANCE', l: 'Endurance' },
  { v: 'WEIGHT_LOSS', l: 'Weight Loss' },
  { v: 'GENERAL_FITNESS', l: 'General Fitness' },
  { v: 'MOBILITY', l: 'Mobility' },
];

const EQUIPMENT = [
  { v: 'barbell', l: 'Barbell' },
  { v: 'dumbbells', l: 'Dumbbells' },
  { v: 'cables', l: 'Cables' },
  { v: 'pullup_bar', l: 'Pull-up bar' },
  { v: 'bench', l: 'Bench' },
  { v: 'rack', l: 'Rack' },
  { v: 'kettlebell', l: 'Kettlebell' },
  { v: 'resistance_bands', l: 'Bands' },
];

const INJURIES = [
  { v: 'lower_back', l: 'Lower back' },
  { v: 'upper_back', l: 'Upper back' },
  { v: 'left_shoulder', l: 'Left shoulder' },
  { v: 'right_shoulder', l: 'Right shoulder' },
  { v: 'left_knee', l: 'Left knee' },
  { v: 'right_knee', l: 'Right knee' },
  { v: 'wrist', l: 'Wrist' },
  { v: 'neck', l: 'Neck' },
];

export default function AICoachV2Page() {
  const router = useRouter();
  const [profile, setProfile] = useState<FitnessProfileData | null>(null);
  const [asymmetry, setAsymmetry] = useState<AsymmetryReport | null>(null);
  const [breakRecovery, setBreakRecovery] = useState<BreakRecovery | null>(null);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    getFitnessProfile().then(setProfile).catch(console.error);
    getAsymmetryReport().then(setAsymmetry).catch(console.error);
    getBreakRecovery().then(setBreakRecovery).catch(console.error);
  }, []);

  async function save(field: string, value: any) {
    if (!profile) return;
    const updated = await updateFitnessProfile({ [field]: value });
    setProfile(updated);
  }

  async function handleGenerate() {
    setGenerating(true);
    try {
      const plan = await generateAIPlan();
      router.push(`/plans/${plan.id}`);
    } finally {
      setGenerating(false);
    }
  }

  if (!profile) {
    return (
      <>
        <div className="flex h-[60vh] items-center justify-center">
          <div className="h-1.5 w-1.5 animate-pulse rounded-full bg-white/40" />
        </div>
      </>
    );
  }

  return (
    <>
      <section style={{ padding: '48px 0 32px' }}>
        <p className="v3-eyebrow-serif">Personalization</p>
        <h1 className="v3-display-2" style={{ marginTop: 8 }}>
          AI<br/>
          <em className="v3-clay" style={{ fontWeight: 300 }}>Coach.</em>
        </h1>
        <p className="v3-body" style={{ color: 'var(--text-2)', marginTop: 16, maxWidth: 560 }}>
          Plan generated by Claude AI based on your goals, weak points, and recovery.
        </p>
      </section>

      {breakRecovery && (
        <div className="mb-16 rounded-3xl border border-[#FF9F0A]/30 bg-[#FF9F0A]/5 p-6">
          <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.25em', color: '#FF9F0A' }}>
            Returning from break
          </div>
          <p className="mt-2 text-base text-white">{breakRecovery.message}</p>
          <p className="mt-1 text-sm text-white/55">
            Intensity reduced to {Math.round(breakRecovery.intensityMultiplier * 100)}%.
          </p>
        </div>
      )}

      {/* Goal */}
      <section className="mb-16">
        <p className="v3-eyebrow">Goal</p>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
          {GOALS.map((g) => (
            <button
              key={g.v}
              onClick={() => save('goal', g.v)}
              className={`rounded-full border px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.15em] transition ${
                profile.goal === g.v
                  ? 'border-white bg-white text-black'
                  : 'border-white/15 text-white/60 hover:border-white/40'
              }`}
            >
              {g.l}
            </button>
          ))}
        </div>
      </section>

      {/* Schedule */}
      <section className="mb-16 grid grid-cols-1 gap-12 sm:grid-cols-3">
        <div>
          <p className="v3-eyebrow">Experience</p>
          <input
            type="number"
            min={0}
            value={profile.experienceMonths ?? 0}
            onChange={(e) => save('experienceMonths', parseInt(e.target.value) || 0)}
            className="w-full border-b border-white/15 bg-transparent py-3 text-3xl font-bold text-white tabular-nums focus:border-white focus:outline-none"
          />
          <div style={{ marginTop: 4, fontSize: 12, color: 'rgba(255,255,255,0.4)' }}>months</div>
        </div>
        <div>
          <p className="v3-eyebrow">Sessions</p>
          <select
            value={profile.daysPerWeek ?? 3}
            onChange={(e) => save('daysPerWeek', parseInt(e.target.value))}
            className="w-full border-b border-white/15 bg-transparent py-3 text-3xl font-bold text-white tabular-nums focus:border-white focus:outline-none"
          >
            {[2, 3, 4, 5, 6].map((d) => (
              <option key={d} value={d} className="bg-black">
                {d}x/week
              </option>
            ))}
          </select>
        </div>
        <div>
          <p className="v3-eyebrow">Duration</p>
          <select
            value={profile.sessionMinutes ?? 45}
            onChange={(e) => save('sessionMinutes', parseInt(e.target.value))}
            className="w-full border-b border-white/15 bg-transparent py-3 text-3xl font-bold text-white tabular-nums focus:border-white focus:outline-none"
          >
            {[30, 45, 60, 75, 90].map((m) => (
              <option key={m} value={m} className="bg-black">
                {m} min
              </option>
            ))}
          </select>
        </div>
      </section>

      {/* Equipment */}
      <section className="mb-16">
        <p className="v3-eyebrow">Equipment</p>
        <div className="flex flex-wrap gap-2">
          {EQUIPMENT.map((eq) => {
            const sel = profile.equipment?.includes(eq.v);
            return (
              <button
                key={eq.v}
                onClick={() => {
                  const cur = profile.equipment || [];
                  save('equipment', sel ? cur.filter((e) => e !== eq.v) : [...cur, eq.v]);
                }}
                className={`rounded-full border px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.15em] transition ${
                  sel
                    ? 'border-white bg-white text-black'
                    : 'border-white/15 text-white/60 hover:border-white/40'
                }`}
              >
                {eq.l}
              </button>
            );
          })}
        </div>
      </section>

      {/* Injuries */}
      <section className="mb-16">
        <p className="v3-eyebrow">Injuries / limitations</p>
        <div className="flex flex-wrap gap-2">
          {INJURIES.map((inj) => {
            const sel = profile.injuries?.includes(inj.v);
            return (
              <button
                key={inj.v}
                onClick={() => {
                  const cur = profile.injuries || [];
                  save('injuries', sel ? cur.filter((e) => e !== inj.v) : [...cur, inj.v]);
                }}
                className={`rounded-full border px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.15em] transition ${
                  sel
                    ? 'border-[var(--accent)] bg-[var(--accent)] text-white'
                    : 'border-white/15 text-white/60 hover:border-white/40'
                }`}
              >
                {inj.l}
              </button>
            );
          })}
        </div>
      </section>

      {/* Generate */}
      <section className="mb-16">
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="group inline-flex items-center gap-3 rounded-full bg-white px-10 py-5 text-base font-semibold tracking-tight text-black transition hover:scale-105 disabled:opacity-30"
        >
          {generating ? 'AI is generating...' : 'Generate plan'}
          {!generating && <span className="transition group-hover:translate-x-1">→</span>}
        </button>
      </section>

      {/* Asymmetry */}
      {asymmetry && (
        <section className="mb-16">
          <p className="v3-eyebrow">Body analysis</p>
          {asymmetry.asymmetries.length > 0 ? (
            <div className="space-y-1">
              {asymmetry.asymmetries.map((a, i) => (
                <div key={i} className="border-b border-white/8 py-6">
                  <div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.25em]" style={{ color: 'var(--accent)' }}>
                    Asymmetry · {a.count}x detected
                  </div>
                  <h2 className="v3-title">{a.joint}</h2>
                  <p className="mt-2 text-sm text-white/55">{a.recommendation}</p>
                </div>
              ))}
            </div>
          ) : (
            <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.4)' }}>No asymmetries detected.</p>
          )}
          <div className="mt-8 border-t border-white/10 pt-6">
            <div className="text-[10px] font-semibold uppercase tracking-[0.25em] text-white/40">
              Fatigue
            </div>
            <p className="mt-2 text-base text-white/75">
              Form drops by{' '}
              <span
                className={
                  asymmetry.fatigue.dropPercentage > 15 ? 'text-[var(--accent)]' : 'text-[var(--sage)]'
                }
              >
                {asymmetry.fatigue.dropPercentage}%
              </span>{' '}
              in the last sets.
            </p>
            <p className="mt-1 text-sm text-white/40">{asymmetry.fatigue.recommendation}</p>
          </div>
        </section>
      )}
    </>
  );
}
